### ISSUE TITLE
Add state classes to `progressive-image`

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#103]
_From @the-j0k3r on June 12, 2018 15:33_

So this is the HTML https://gist.github.com/the-j0k3r/bd3793aa5dd2d19b421cb296db70434c/2c176470a2d4432331c9a9870795a34c047faf2d

So with the CSS below I get this result.
```css
.card-image .ouc-responsive-image
{
	background-image: none !important;
	/*background-image: url("https://openusercss.org/img/main.bg-x640.png") !important; */
	background: linear-gradient(var(--hover-background), var(--main-background)) !important;
}
```
![screenshot-2018-6-12 openusercss 1](https://user-images.githubusercontent.com/31389848/41300501-caf68300-6e5d-11e8-9279-1d87fe3fd869.png)

The problem is themes with actual screenshots are also affected by this, so Im trying to target the image `main.bg-x640.png` directly

Ive tried adding `img[src$="main.bg-x640.png"]` `img[src^="main.bg-x640.png"]` or `img[src*="main.bg-x640.png"]` to no avail, Ive tried on it on and adding to selectors that work.

As an amateur this is a head scratcher. Some assist would be nice.

_Copied from original issue: OpenUserCSS/OpenUserCSS-DeepDark#22_
