### ISSUE TITLE
Place style rating under screenshot.

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#104]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| rating is shown on the screenshot area | it should show below before author? |

## Steps to Reproduce the Problem

The problem is the positive rating vs no rating is likely to be less visible depending on the screenshot the user uploads for his/hers style.

Point and case
You can see that @DecentM theme screenshot is bright and no rating is already hard to see.
This problem varies with default theme  for same reason.

### No style (deaflut)
![screenshot-2018-6-14 openusercss 4](https://user-images.githubusercontent.com/31389848/41438341-dd0f27dc-701e-11e8-8ae0-53e338192cb9.png)

### Styled still hard to see
![screenshot-2018-6-14 openusercss 3](https://user-images.githubusercontent.com/31389848/41437062-81655c24-701b-11e8-8f0f-de4ef8bbe1aa.png)

## A mock of proposal.

![screenshot-2018-6-14-openusercss 3](https://user-images.githubusercontent.com/31389848/41438226-8117ca92-701e-11e8-8ce0-19e510ae9171.png)

## Environment details

  - Site version: all till now
  - Browser and version: all under the sun
  - Installed extensions: everything if I could find more I would add them too :)
  - Operating system: None, I plug the intra-webs into ma brain :)

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment]
Thanks for the idea!  
I agree that it can be hard to see the rating depending on the screenshot below it

**Comment by the-j0k3r** [comment]
Your theme is impossible to see even default :) This is design 101 dont let the unknown be an issue.

**Comment by the-j0k3r** [comment]
Ive done this in theme in conjunction with the fix for #103 it works great.

![screenshot-2018-6-15 openusercss](https://user-images.githubusercontent.com/31389848/41444651-5668bb58-703c-11e8-941e-78f145771e64.png)

<details>
  <summary><strong>OpenUserCS­S Tweaks</strong> (click to expand)</summary>

```css
	.ouc-responsive-image.-img-main-bg-x640-png
	{
		background:
			repeating-linear-gradient(
				45deg,
				transparent,
				transparent 10px,
				var(--hover-background) 10px,
				var(--main-background) 80px),
			linear-gradient(
				to bottom,
				var(--hover-background),
				var(--main-background)) !important;
	}
	.ouc-screenshot-overlay .is-pulled-right.vue-star-rating
	{
		margin-top: 180px !important;
}
```
</details>
</summary>

## Click [here to install](https://git.io/vhPwN) as userCSS
