### ISSUE TITLE
Forced scrollbars

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#30]
From #19, there could be a dynamic scrollbar, which would solve the empty, disabled scollbar on pages that fit the first fold.

It should cover for cutom scrollbars too

**Comment by DecentM** [comment]
@narcolepticinsomniac
I tried applying the style you wrote. While it works in getting rid of the jumping, it introduces a [white column on the right](https://i.imgur.com/6H4klHl.png). I tried changing widths and padding sizes to no avail.
Does that appear for you? I'd love to have this be a part of the site if this could be fixed.

Also, I managed to achieve the same effect (with the same issue) with this:
```css
.dynamic-width-root {
  padding-left: calc((100vw - 100%) / 2);
  padding-right: calc((100vw - 100%) / 2);
}
```
