### ISSUE TITLE
Some fields dont have a font defined or font is not provided

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#95]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| provide unusual fonts | it doesn't afaict |

## Steps to Reproduce the Problem

  1. view any `.content h1, .content h3, .label, .card-header-title p,  .card-header-title label, .card-header-title, .title.is-7` selectors on website
  1. notice that you dont have `Nunito` font your browser will use whatever font as replacement.
  1. Notice theme author fields in card is wrong e.g. e.g hyperfekt shows as hyperfel 

Name borkage screenshots hyperfekt shows as hyperfel 
![screenshot-2018-6-12 openusercss](https://user-images.githubusercontent.com/31389848/41290295-6376c4e2-6e44-11e8-975e-821cbca64e76.png)
![screenshot-2018-6-12 openusercss 1](https://user-images.githubusercontent.com/31389848/41290296-63c4dac4-6e44-11e8-8008-02eb7c08f4a5.png)

Other fields
without
![screenshot-2018-6-12 openusercss 3](https://user-images.githubusercontent.com/31389848/41290484-ef5f963c-6e44-11e8-874d-cb38d39b422c.png)
with
![screenshot-2018-6-12 openusercss 4](https://user-images.githubusercontent.com/31389848/41290485-ef7deb0a-6e44-11e8-9f65-24a167887138.png)

without
![screenshot-2018-6-12 openusercss 2](https://user-images.githubusercontent.com/31389848/41290487-ef9c9712-6e44-11e8-893f-86d9dd94244c.png)

with
![screenshot-2018-6-12 openusercss 5](https://user-images.githubusercontent.com/31389848/41290621-5a9443d0-6e45-11e8-8cb7-07f79a11d3b6.png)

a temporary solution was to add
```css
	/* Temporarily assign an existing font since website is not providing any for these fields 
	This also fixes username showing wrong e.g hyperfekt -> hyperfel */
	.content h1, .content h3, .label, .card-header-title p,  .card-header-title label, .card-header-title, .title.is-7
	{
		font-family: Nunito, monaco, monospace, sans-serif !important;
	}	
	/* size adjustment required while font is borked*/
	.title.is-7
	{
		font-size: 1.23333rem !important;
	}
```
Into OpenUserCSS Deepdark theme, at least something works for now,

## Environment details

  - Site version: 1.0.0 (worked fine in 0.9.7)
  - Browser and version: ANY but FF 66.0.2 will suffice.
  - Installed extensions: not applicable
  - Operating system: Not applicable

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>
